<?php
/**
 * Created by PhpStorm.
 * User: Bree
 * Date: 3/25/17
 * Time: 12:33 PM
 */
/* DRUPAL HOOKS */

/**
 * Implements hook_theme().
 */
function phparch_theme($existing, $type, $theme, $path) {
  return array(
    'phparch_current_weather' => array(
      'variables' => array(
        'location' => NULL,
        'zipcode' => NULL,
        'temperature' => NULL,
        'description' => NULL,
        'zipurl' => NULL,
      ),
      'template' => 'phpa-current-weather',
    ),
    'phparch_current_weather_block' => array(
      'variables' => array(
        'location' => NULL,
        'zipcode' => NULL,
        'temperature' => NULL,
        'description' => NULL,
        'zipurl' => NULL,
      ),
      'template' => 'phpa-current-weather-block',
    ),
  );
}